=== vhurtado89/CECS475/Assign5/assign 5_3/books.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="books" type="bookInformation" />

  <xs:complexType name="bookInformation">
    <xs:sequence>
       <xs:element name="book" minOccurs="1" maxOccurs="unbounded" type="BookType" />
    </xs:sequence>
  </xs:complexType>  
  
  <xs:complexType name="BookType">
    <xs:sequence>
      <xs:element name="author" type="authorType" />
      <xs:element  name="bookinfo" type="books_Type"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="authorType">
    <xs:sequence>
      <xs:element name="name" type="nameType" />
      <xs:element name="contact" type="contactType" />
    </xs:sequence>
    <xs:attribute name="auid" use="required" type="auIdType"/>
  </xs:complexType>

  <xs:complexType name="books_Type">
    <xs:sequence>
      <xs:element name="title" type="titleType" />
      <xs:element name="edition" type="editionType" />
      <xs:element name="isbn" type="isbnType" />
      <xs:element name="price" type="priceType" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="nameType">
    <xs:sequence>
      <xs:element name="fname" type="fnameType" />
      <xs:element name="lname" type="lnameType"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="contactType">
    <xs:sequence>
      <xs:element name="email" type="emailType" />
      <xs:element name="phone" type="phoneType" />
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="titleType">
    <xs:restriction base="xs:string" />
  </xs:simpleType>

  <xs:simpleType name="editionType">
    <xs:restriction base="xs:string" />
  </xs:simpleType>


  <xs:simpleType name="isbnType">
    <xs:restriction base="xs:positiveInteger" />
  </xs:simpleType>

  <xs:simpleType name="priceType">
    <xs:restriction base="xs:decimal"/>
  </xs:simpleType>

  <xs:simpleType name="fnameType">
    <xs:restriction base="xs:string" />
  </xs:simpleType>

  <xs:simpleType name="lnameType">
    <xs:restriction base="xs:string" />
  </xs:simpleType>


  <xs:simpleType name="emailType">
    <xs:restriction base="xs:string">
      <xs:pattern value="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="phoneType" >
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{3}-[0-9]{7}" />
     </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name ="auIdType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{3}"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== vhurtado89/CECS475/Assign5/assign 5_3/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<books
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="books.xsd">
  <book>
    <author auid ="123">
      <name>
        <fname>Abbey</fname>
        <lname>Deitel</lname>
      </name>
      <contact>
        <email>aaa@bbb.com</email>
        <phone>562-1119999</phone>
      </contact>
    </author>
    <bookinfo>
      <title>C++ Programming</title>
      <edition>1st Edition</edition>
      <isbn>123456</isbn>
      <price>50.90</price>
    </bookinfo>
  </book>
  <book>
    <author auid ="623">
      <name>
        <fname>John</fname>
        <lname>Nguyen</lname>
      </name>
      <contact>
        <email>eee@bbb.com</email>
        <phone>562-2229999</phone>
      </contact>
    </author>
    <bookinfo>
      <title>Java Programming</title>
      <edition>3th Edition</edition>
      <isbn>563456</isbn>
      <price>80.00</price>
    </bookinfo>
  </book>
</books>
